'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AdresaDostave

    '''<summary>
    '''imePrezime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imePrezime As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents email As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl

    '''<summary>
    '''adresa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents adresa As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''grad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grad As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''postBr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents postBr As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''brTel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents brTel As Global.System.Web.UI.HtmlControls.HtmlInputText
End Class
